apiVersion: v1
kind: Service
metadata:
  name: swiggy-app-lb
  labels:
    app: swiggy-app-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: swiggy-app-lb
